motto: <p class="moto">Distributed data processing</p>
footer: |
    <footer>
    <p>
    <a href="mailto:sasha@shards.io">Aliaksandr Aliashkevich</a> <br>
    Prague, Czech Republic
    </p>
    </footer>
include: [./doc/]

markdown: redcarpet
