motto: <p class="moto">Cloud database platform</p>
footer: |
    <footer>
    <p>
    This project is maintained by <br> 
    <a href="mailto:sasha@shards.io">Aliaksandr Aliashkevich</a> <br>
    Prague, Czech Republic
    </p>
    </footer>
include: [./doc/]

markdown: redcarpet
