motto: <p class="moto">The way from data to the knowledge</p>
footer: |
    <footer>
    <p>
    This project is maintained by <a href="mailto:sasha@shards.io">SUFLEX s.r.o.</a><br>
    Prague, Czech Republic</p>
    </footer>

